### ISSUE TITLE
Support configuration of rack-aware partition distribution 

### ISSUE THREAD

**Issue by menski** [camunda-cloud/zeebe#6266]
**Is your feature request related to a problem? Please describe.**

In a multi-datacenter setup it is required to control which partitions are located in which data center. It also is advantageous if a user can indicate which brokers should be priority leader for a partition, for example to indicate the preferred leader balance between the data centers.

**Describe the solution you'd like**

In the cluster configuration I can specify a manual mapping of partitions hosted by the broker. This will be used when defining the partition membership on startup, and ignore the default partition layout over the cluster. Additionally a user can specify a priority for a leader to be leader of a specific partition. This priority should be used to influence a heuristic in the leader election process which prefers the prioritized broker. 

**Describe alternatives you've considered**

- Setup the cluster in a way that the current partition layout leads to an even distribution
- Restart the cluster until the expected leader balancing happened

**Additional context**

If the user chooses to manually configure the partition layout, its there responsibility to ensure that partitions have the correct number of replicas and are evenly distributed. The broker will only perform sanity checks possible from a single broker configuration.

**Comment by npepinpe** [comment]
I would propose always specifying the complete partition scheme. My reasoning is that you typically have a single configuration file which all brokers load via a `ConfigMap`, with some environment variables overload. So it seems natural to me that you'd specify in that configuration file the complete partitioning scheme. For example, given 5 brokers, 5 partitions, replication factor 3:

```yaml
zeebe:
  broker:
    experimental:
      partitions:
        0: [1, 3, 5]
        1: [2, 4, 5]
        2: [1, 3, 5]
        3: [2, 4, 3]
        4: [1, 2, 4]
```

This way the scheme is centralized, it's always the same, and you can do more than basic sanity checks - you can verify that the replication factor is correct, that all partitions are fully distributed, etc.

**Comment by npepinpe** [comment]
I spent some time today to think about this, and here's my proposal:

We introduce a new experimental configuration parameter which lets you switch between two partitioning scheme: round robin, and fixed. Round robin is the default scheme, requires no additional configuration, and is what's currently used in Zeebe.

The fixed scheme is the one where a user can provide an exhaustive mapping of nodes (and optionally priorities) for each partition. Here exhaustive means, all partitions must be configured - if any partition is missing, or does not have the required amount of replicas, the broker will fail to start.

## Configuration

The configuration would look like this (`clusterSize=3`, `replicationFactor=3`, `partitionCount=3`):

```yaml
# This setting allows you to configure how partitions are distributed amongst the node of the
# clusters. It currently supports to partitioning schemes: ROUND_ROBIN, and FIXED.
#
# ROUND_ROBIN is the default partitioning scheme. To enable it, set `scheme` to `ROUND_ROBIN`;
# not extra configuration is required. To understand how it will distribute the partitions,
# refer to the documentation:
#   https://docs.camunda.io/docs/product-manuals/zeebe/technical-concepts/partitions#partition-distribution
#
# The FIXED partitioning scheme allows users with non-traditional deployments to manual
# distribute the partitions across their set of brokers. This can be useful, for example, if
# you want to deploy a cluster across multiple data centers with some replication guarantees.
# See below for details on how to configure it.
#
# This setting can also be overridden using the environment variable ZEEBE_BROKER_EXPERIMENTAL_PARTITIONING
partitioning:
  # The partitioning scheme to use. Can be one of: ROUND_ROBIN, FIXED. Defaults to
  # ROUND_ROBIN.
  scheme: FIXED

  # The FIXED partitioning scheme configuration. This must be an exhaustive mapping of all
  # partitions to a set of brokers. If any partitions are not configured, the broker will not
  # start.
  #
  # For each partition, you must specify its partition ID (ranging from 1 to
  # (partitionCount - 1)), and the set of nodes which will manage it. This must be a subset
  # of nodes whose IDs are valid within your cluster. This means with node IDs ranging from 0
  # to the (clusterSize - 1), without any repeated IDs. This subset must have the same amount
  # of nodes as the replication factor, otherwise the broker will not start.
  #
  # If you are using priority election, then you can also specify the priorities for each
  # nodes. If you do not provide a priority, it will default to 1, which will still work but
  # can have unintended consequences. Finally, the highest configured priority will become the
  # target priority for that partition.
  #
  fixed:
    - partitionId: 1
      nodes:
        - nodeId: 0
          priority: 1
        - nodeId: 1
          priority: 2
        - nodeId: 2
          priority: 3
    - partitionId: 2
      nodes:
        - nodeId: 0
          priority: 3
        - nodeId: 1
          priority: 2
        - nodeId: 2
          priority: 1
    - partitionId: 3
      nodes:
        - nodeId: 0
          priority: 2
        - nodeId: 1
          priority: 3
        - nodeId: 2
          priority: 2
```

While this is somewhat verbose, it's pretty similar to most YAML based configuration you'll find around, e.g. Kubernetes configuration. Again, note that if you're not using the priority election, the priority can be simply omitted, which reduces a bit the verbosity.

Another thing to note, it would be technically valid to specify more partitions on some nodes than others. Above, the example was evenly distributing them out of necessity, but technically as long as they all have the required number of replicas it doesn't matter from a correctness point of view.

## Implementation

The first step implement it is to extract the partition distributor into an injectable component. So, first:

- [ ] Extract a `PartitionDistributor` interface from `PartitionDistributor`, and rename the implementation to `RoundRobinPartitionDistributor`.
- [ ] Allow configuring a custom `PartitionDistributor`, starting from the `RaftPartitionGroupFactory` down to the `RaftPartitionGroup` configuration, such that it will be used when building the partitions.
- [ ] Introduce a new `PartitioningCfg` under `ExperimentalCfg` which maps to the configuration defined above.
- [ ] Introduce a new `FixedPartitionDistributor` implementation which distributes partition explicitly based on the above configuration, and wire it in `RaftPartitionGroupFactory` from the new `PartitioningCfg` (or `FixedPartitionCfg` sub component).
- [ ] Add unit tests related to the configuration and its validation (as described above)
- [ ] Add acceptance tests which start a cluster with a fixed configuration, and verify via `/actuator/partitions` that the partitions belong to the correct node. Make sure the fixed configuration is different from the round robin's automated configuration.
- [ ] Add documentation of the configuration in `broker.yaml.template` and `broker.standalone.yaml.template`
- [ ] Add a small documentation section in [here](https://docs.camunda.io/docs/product-manuals/zeebe/technical-concepts/partitions) describing this new __experimental__ feature (note: make sure it's quite clear that it is experimental and subject to change)

> NOTE: the whole point about it being experimental is to allow users which need this to test it out, and for us gather feedback, act on it (for example change the configuration), and then promote it once we're satisfied it covers most use cases.
