### ISSUE TITLE
Backport non-memory related RocksDB configuration to 0.26

### ISSUE THREAD

**Issue by npepinpe** [camunda-cloud/zeebe#6929]
**Description**

We introduced optimized RocksDB configuration in 1.0 to soft cap the memory usage, ensure snapshots are not fragmented, and generally limit the the resource consumption of RocksDB (while keeping the performance on par).

While the solution relied on dropping the high number of column families - which would break backwards compatibility - we can at least back port part of the settings which are not related to having multiple column families. So all non-column family settings, and all non-memory related (no cache, no memtable) column family settings.

This includes not only the changes in the zb-db module but also the new `RocksDbCfg` usage in `BrokerCfg` (though removing any non-applicable settings).

NOTE: If the user specifies custom RocksDB config, then we should keep the old behavior and have that override any column family settings we might specify.

**Comment by npepinpe** [comment]
@korthout - this would also include the `maxOpenFiles` setting, which should fix your support case. With this issue closed we could immediately do a 0.26.4 release.

**Comment by deepthidevaki** [comment]
In 0.26 rocks db configuration is under DataCfg. But in 1.0 we moved it to experimental config. Where should we expose the new configs in 0.26.*? To keep compatibility, we should keep then under DataCfg. However then we would be exposing many unstable configurations.

**Comment by npepinpe** [comment]
We can do both - keep the old RocksDbCfg in DataCfg (rename the class as this has no bearing on the user input), and use it as a default value for the new config's user properties. wdyt?

**Comment by deepthidevaki** [comment]
Alternatively: Keep the (existing) columnFamilyOptions in DataCfg, and add the new ones in experimental. 
```
zeebe:
  broker:
    data:
      rocksdb:
        columnFamilyOptions:
          compaction_pri: "kOldestSmallestSeqFirst"
          write_buffer_size: 67108864
    experimental:
      rocksdb:
        enableStatistics: true
        memoryLimit: 32MB
        maxOpenFiles: 3
        maxWriteBufferNumber: 3
        minWriteBufferNumberToMerge: 3
        ioRateBytesPerSecond: 4096
        disableWal: true
```
