### ISSUE TITLE
zeebe v1.03 disk IO is too higher

### ISSUE THREAD

**Issue by yzhengwei** [camunda-cloud/zeebe#7740]
I created a 5 node zeebe cluster using an IOPS 9000 disk with a read/write speed of 350MB/S. When I upgrade the Zeebe cluster from V0.26 to V1.03, the disk I/O increases obviously and reaches the performance bottleneck. What should I do?

```shell
Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
vda               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
vdb               0.00  1286.00    0.00 2570.00     0.00 14880.00    11.58     1.20    0.47    0.00    0.47   0.36  91.55

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           2.40    0.00    2.90   28.25    0.00   66.46

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
vda               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
vdb               0.00  1271.50    0.00 2482.50     0.00 14588.00    11.75     1.16    0.47    0.00    0.47   0.37  92.80

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           2.15    0.00    2.65   29.84    0.00   65.36

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
vda               0.00     0.00    0.00    0.50     0.00    34.00   136.00     0.00    1.00    0.00    1.00   2.00   0.10
vdb               0.00  1268.00    0.00 2714.00     0.00 15134.00    11.15     1.21    0.44    0.00    0.44   0.35  94.75

```

The zeebe config like this:

```yaml
zeebe:
  broker:
    stepTimeout: 5m
    gateway:
      enable: true
      network:
        port: 26500
        minKeepAliveInterval: 30s
      cluster:
        requestTimeout: 15s
      threads:
        managementThreads: 2000
      monitoring:
        enabled: true
      longPolling:
        enabled: true
    network:
      portOffset: 0
      maxMessageSize: 4MB
      commandApi:
        host: 10.21.91.186
        port: 26501
      internalApi:
        host: 10.21.91.186
        port: 26502
      monitoringApi:
        port: 10106
    data:
      directory: /data/zeebe
      logSegmentSize: 128MB
      snapshotPeriod: 15m
    cluster:
      nodeId: 1
      partitionsCount: 5
      replicationFactor: 3
      clusterSize: 5
      initialContactPoints : [ "10.21.93.236:26502","10.21.91.186:26502","10.21.89.44:26502","10.21.90.133:26502","10.21.91.143:26502"  ]
      clusterName: zeebe-cluster
      membership:
        probeTimeout: 2s
    threads:
      cpuThreadCount: 2
    backpressure:
      enabled : true
      algorithm: "vegas"
      vegas:
        initialLimit: 20
        alpha: 3
        beta: 6
    exporters:
      elasticsearch:
        className: io.camunda.zeebe.exporter.ElasticsearchExporter
        args:
          url: http://zeebe-es.zpidc.com:9200
          index:
            prefix: ms
            deployment: true
```

**Comment by npepinpe** [comment]
Hi @yzhengwei! Zeebe will always be performing a lot of I/O by nature, as you have to keep in mind that it has to persist everything - in a way, it is its own database. We wouldn't expect an increase in I/O without an increase in throughput however :slightly_smiling_face: 

Can you elaborate on the differences you observed? What kind of load are you running on Zeebe, what's your throughput for that load (e.g. process instances completed per second, or whatever is appropriate for your test), what was previously the I/O throughput (both read and write) and what it is now, etc.

And also about the environment in which your run Zeebe - is this network storage? SSD drive? Local SSD (as opposed to networked SSD)? HDD? NVME?

Regarding your settings, one thing that jumped to me is that you only allocate 2 CPU threads, but you have 3 partitions per broker. Worst case scenario, a single broker is leader for all partitions. Rule of thumb is to allocate 1 cpuThread and 1 ioThread per partition, with one extra CPU thread for the transport layer. So in your case, I would try with:

```yaml
zeebe:
  broker:
    threads:
      cpuThreadCount: 4
      ioThreadCount: 3
```
