### ISSUE TITLE
Smoketest fails with versions missing for agrona

### ISSUE THREAD

**Issue by korthout** [camunda-cloud/zeebe#8265]
**Description**

Pull requests are seeing the following error failing the smoke tests:
>Error:  Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java (default) on project zeebe-protocol: Execution default of goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java failed: Plugin org.codehaus.mojo:exec-maven-plugin:3.0.0 or one of its dependencies could not be resolved: Failed to collect dependencies at org.codehaus.mojo:exec-maven-plugin:jar:3.0.0 -> uk.co.real-logic:sbe-tool:jar:1.25.0 -> org.agrona:agrona:jar:[1.13,1.14): No versions available for org.agrona:agrona:jar:[1.13,1.14) within specified range -> [Help 1]

**Comment by korthout** [comment]
The problem was the cached .m2 folder. It contained wrong information about either agrona or the sbe-tool.

For future situations, here's the solution:

- Find the .m2/repository location (it's logged in the logs and differs per OS)
- clear the broken cache parts by removing the respective folders from the local repository

In the related case in https://github.com/camunda-cloud/zeebe/pull/8233 we cleared the cache with 369da6f92757ffafcd789b526047e6feb6cbbc32:
```yml
- name: Clear broken cache parts
   uses: JesseTG/rm@v1.0.2
   with:
     path: C:\Users\runneradmin\.m2\repository\org\agrona\agrona
- name: Clear broken cache parts
   uses: JesseTG/rm@v1.0.2
   with:
     path: C:\Users\runneradmin\.m2\repository\uk\co\real-logic\sbe-tool
```
